In [55]:
import torch 
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.autograd as autograd
from torchvision import datasets, transforms


In [3]:
x = torch.Tensor(2, 3)

In [5]:
x


tensor([[ 0.0000e+00,  4.6566e-10,  0.0000e+00],
        [ 4.6566e-10,  4.2981e+21,  6.3828e+28]])

In [7]:
x = torch.rand(2, 3)
x

tensor([[ 0.2541,  0.0715,  0.6239],
        [ 0.8283,  0.1828,  0.7581]])

In [9]:
x = torch.ones(2, 3)
y = torch.ones(2, 3) * 2
x + y

tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.]])

In [11]:
y[:, 1] = y[:, 1] + 1

In [12]:
y

tensor([[ 2.,  4.,  2.],
        [ 2.,  4.,  2.]])

In [31]:
x = Variable(torch.ones(2, 2) * 2, requires_grad = True)


In [32]:
z = 2 * (x * x) + 5 * x

In [33]:
z.backward(torch.ones(2, 2))

In [36]:
print(x.grad)

tensor([[ 13.,  13.],
        [ 13.,  13.]])


In [42]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28 * 28, 200)
        self.fc2 = nn.Linear(200, 200)
        self.fc3 = nn.Linear(200, 10)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return F.log_softmax(x)
    

In [43]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=200, bias=True)
  (fc3): Linear(in_features=200, out_features=10, bias=True)
)


In [63]:
learning_rate = 0.01
batch_size = 200
epochs = 10
log_interval = 10
optimizer = optim.SGD(net.parameters(), lr = learning_rate, momentum = 0.9)
criterion = nn.NLLLoss()

In [61]:
train_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=True, download=True,
                       transform=transforms.Compose([
                           transforms.ToTensor(),
                           transforms.Normalize((0.1307,), (0.3081,))
                       ])),
        batch_size=batch_size, shuffle=True)

In [62]:
test_loader = torch.utils.data.DataLoader(
        datasets.MNIST('../data', train=False, transform=transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize((0.1307,), (0.3081,))
        ])),
        batch_size=batch_size, shuffle=True)

In [68]:
for epoch in range(epochs):
    for batch_idx, (data, target) in enumerate(train_loader):
        data, target = Variable(data), Variable(target)
        data = data.view(-1, 28 * 28)
        optimizer.zero_grad()
        net_out = net(data)
        loss = criterion(net_out, target)
        loss.backward()
        optimizer.step()
        if batch_idx % log_interval == 0:
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_loader.dataset),
                           100. * batch_idx / len(train_loader), loss.data[0]))

/Library/Python/2.7/site-packages/ipykernel_launcher.py:12: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if sys.path[0] == '':
/Library/Python/2.7/site-packages/ipykernel_launcher.py:13: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  del sys.path[0]


Train Epoch: 0 [0/60000 (0%)]	Loss: 0.004177
Train Epoch: 0 [2000/60000 (3%)]	Loss: 0.005419
Train Epoch: 0 [4000/60000 (7%)]	Loss: 0.002463
Train Epoch: 0 [6000/60000 (10%)]	Loss: 0.004902
Train Epoch: 0 [8000/60000 (13%)]	Loss: 0.002734
Train Epoch: 0 [10000/60000 (17%)]	Loss: 0.007696
Train Epoch: 0 [12000/60000 (20%)]	Loss: 0.006386
Train Epoch: 0 [14000/60000 (23%)]	Loss: 0.003025
Train Epoch: 0 [16000/60000 (27%)]	Loss: 0.005662
Train Epoch: 0 [18000/60000 (30%)]	Loss: 0.003421
Train Epoch: 0 [20000/60000 (33%)]	Loss: 0.012084
Train Epoch: 0 [22000/60000 (37%)]	Loss: 0.001939
Train Epoch: 0 [24000/60000 (40%)]	Loss: 0.003057
Train Epoch: 0 [26000/60000 (43%)]	Loss: 0.004211
Train Epoch: 0 [28000/60000 (47%)]	Loss: 0.002117
Train Epoch: 0 [30000/60000 (50%)]	Loss: 0.003799
Train Epoch: 0 [32000/60000 (53%)]	Loss: 0.009131
Train Epoch: 0 [34000/60000 (57%)]	Loss: 0.003730
Train Epoch: 0 [36000/60000 (60%)]	Loss: 0.004395
Train Epoch: 0 [38000/60000 (63%)]	Loss: 0.007079
Train Epoch

Train Epoch: 5 [32000/60000 (53%)]	Loss: 0.003585
Train Epoch: 5 [34000/60000 (57%)]	Loss: 0.003570
Train Epoch: 5 [36000/60000 (60%)]	Loss: 0.005261
Train Epoch: 5 [38000/60000 (63%)]	Loss: 0.003520
Train Epoch: 5 [40000/60000 (67%)]	Loss: 0.002688
Train Epoch: 5 [42000/60000 (70%)]	Loss: 0.005120
Train Epoch: 5 [44000/60000 (73%)]	Loss: 0.001479
Train Epoch: 5 [46000/60000 (77%)]	Loss: 0.003905
Train Epoch: 5 [48000/60000 (80%)]	Loss: 0.003913
Train Epoch: 5 [50000/60000 (83%)]	Loss: 0.001653
Train Epoch: 5 [52000/60000 (87%)]	Loss: 0.004986
Train Epoch: 5 [54000/60000 (90%)]	Loss: 0.004558
Train Epoch: 5 [56000/60000 (93%)]	Loss: 0.002781
Train Epoch: 5 [58000/60000 (97%)]	Loss: 0.003947
Train Epoch: 6 [0/60000 (0%)]	Loss: 0.001753
Train Epoch: 6 [2000/60000 (3%)]	Loss: 0.001529
Train Epoch: 6 [4000/60000 (7%)]	Loss: 0.001149
Train Epoch: 6 [6000/60000 (10%)]	Loss: 0.002521
Train Epoch: 6 [8000/60000 (13%)]	Loss: 0.003711
Train Epoch: 6 [10000/60000 (17%)]	Loss: 0.002662
Train Epoch

In [72]:
test_loss, correct = 0, 0
for data, target in test_loader:
    data, target = Variable(data, volatile = True), Variable(target)
    data = data.view(-1, 28 * 28)
    net_out = net(data)
    test_loss += criterion(net_out, target).data[0]
    print(criterion(net_out, target).data)
    pred = net_out.data.max(1)[1]
    correct += pred.eq(target.data).sum()
    
test_loss /= len(test_loader.dataset)
print("\nTest set: Average loss: {:.4f}, Accuracy: {} / {} ({:.0f}%)\n".format(
    test_loss, correct, len(test_loader.dataset), 100. * correct / len(test_loader.dataset)
))    

/Library/Python/2.7/site-packages/ipykernel_launcher.py:3: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Python/2.7/site-packages/ipykernel_launcher.py:12: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  if sys.path[0] == '':
/Library/Python/2.7/site-packages/ipykernel_launcher.py:6: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  


tensor(1.00000e-03 *
       3.8482)
tensor(0.1163)
tensor(0.1790)
tensor(1.00000e-02 *
       7.3233)
tensor(1.00000e-02 *
       3.7980)
tensor(1.00000e-02 *
       3.1419)
tensor(1.00000e-02 *
       8.2084)
tensor(0.1410)
tensor(0.1105)
tensor(1.00000e-02 *
       2.8443)
tensor(0.1117)
tensor(0.1207)
tensor(1.00000e-02 *
       4.0165)
tensor(1.00000e-02 *
       5.9876)
tensor(0.1137)
tensor(0.1045)
tensor(1.00000e-02 *
       7.3176)
tensor(1.00000e-02 *
       9.3929)
tensor(1.00000e-02 *
       2.5744)
tensor(0.1563)
tensor(1.00000e-02 *
       2.6546)
tensor(0.1136)
tensor(1.00000e-02 *
       4.9137)
tensor(1.00000e-02 *
       6.9535)
tensor(1.00000e-02 *
       9.3072)
tensor(1.00000e-02 *
       3.1273)
tensor(1.00000e-02 *
       6.4904)
tensor(1.00000e-02 *
       8.7859)
tensor(1.00000e-02 *
       7.6098)
tensor(0.1621)
tensor(1.00000e-02 *
       3.8164)
tensor(1.00000e-02 *
       4.8028)
tensor(1.00000e-02 *
       6.4370)
tensor(1.00000e-02 *
       4.5228)
tensor(